apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::049101793176:role/UdacityFlaskDeployCBKubectlRole
      username: build
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::049101793176:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1JGJTHOF7QE9U
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2021-11-05T08:24:07Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1036"
  uid: 89560219-8a0a-4407-940a-cb966ccff9f7
